services:
  - type: web
    name: gemini-landmark-app
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.0"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
